baseURL = "https://eva19950630.github.io/"
languageCode = "zh-tw"
title = "Syuan Tech Blog"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
    since = 2018
    author = "Syuan Shih"                           # Author's name
    avatar = "/avatar.png"           # Author's avatar
    subtitle = "Where theres a will theres a way."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    # license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "eva19950630"
    Email   = "fun910347@gmail.com"
    Instagram = "eva19950630"
    Facebook = "eva19950630"
    # Twitter = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

